/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.DocumentoSoporte;

import Controlador.Alertas.ControladorAlertas;
import Utilidades.Constantes;
import clases.Instancias;
import Modelo.Terceros.ModeloContacto;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sebastian.londono
 */
public class squemaDocumentoSoporte extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();

    private static final String ERRORDIAN = "ERRORDIAN";
    private static final String ERROR = "ERROR";

    public squemaDocumentoSoporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionesDocumentoSoporte(ModeloContacto datosContacto, boolean esDesdeEgreso) {

        String descripcionContacto = esDesdeEgreso ? "tercero" : "vendedor"; 
        List<Object> errores_validacion = new ArrayList<>();

        try {
            Socket s = new Socket("www.google.com", 80);
            if (s.isConnected()) {
                System.out.println("Comprando electronicamente");
            }
        } catch (Exception e) {
            errores_validacion.add("No se puede comprar electrónicamente sin conexión a internet");
        }

        String identificadorCliente = Constantes.leerIdentificadorCliente();
        int numeroFacturasDisponibles = Integer.parseInt(instancias.getSqlPagos().obtenerNumeroConsecutivo(identificadorCliente)[0].toString());

        if (numeroFacturasDisponibles <= 0) {
            errores_validacion.add("No tiene movimientos electrónicos disponibles, comuniquiese con el proveedor");
        } else if (numeroFacturasDisponibles < 5) {
            alerts.alert("Quedan solo " + numeroFacturasDisponibles + " movimientos electrónicos.");
        } else {
            System.out.println("numero de movimientos: " + numeroFacturasDisponibles);
        }

        if (null == datosContacto.getId() || Constantes.CLIENTE_POR_DEFECTO.equals(datosContacto.getId())) {
            errores_validacion.add("Debe cargar un " + descripcionContacto + " para facturar electrónicamente");
        }

        if (datosContacto.getDepartamento() != null) {
            if ("".equals(datosContacto.getDepartamento())) {
                errores_validacion.add("El " + descripcionContacto + " debe tener un departamento");
            }
        } else {
            errores_validacion.add("El " + descripcionContacto + " debe tener un departamento");
        }

        if (datosContacto.getCiudad() != null) {
            if ("".equals(datosContacto.getCiudad())) {
                errores_validacion.add("El " + descripcionContacto + " debe tener una ciudad");
            }
        } else {
            errores_validacion.add("El " + descripcionContacto + " debe tener una ciudad");
        }

        if (datosContacto.getDireccion() != null) {
            if (datosContacto.getDireccion().equals("")) {
                errores_validacion.add("El " + descripcionContacto + " debe tener una dirección");
            }
        } else {
            errores_validacion.add("El " + descripcionContacto + " debe tener una dirección");
        }

        if (datosContacto.getEmail() != null) {
            if (datosContacto.getEmail().equals("")) {
                errores_validacion.add("El " + descripcionContacto + " debe tener un email");
            }
        } else {
            errores_validacion.add("El " + descripcionContacto + " debe tener un email");
        }

        if (null != datosContacto.getId() && datosContacto.getId().contains("-")) {
            if (null == datosContacto.getId().split("-")[1]) {
                errores_validacion.add("El " + descripcionContacto + " debe tener dígito de verificación");
            }
        } else {
            errores_validacion.add("El " + descripcionContacto + " debe tener dígito de verificación");
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
