/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.Tesoreria;

import Validaciones.Compras.*;
import Controlador.Alertas.ControladorAlertas;
import Enums.enumTipoDocumento;
import Utilidades.Constantes;
import clases.Instancias;
import clases.big;
import Modelo.Terceros.ModeloContacto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author sebastian.londono
 */
public class squemaEgresos extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();
    private String simboloMoneda = instancias.getSimbolo();

    public squemaEgresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionesEgreso(ModeloContacto datosVendedor, String tipoEgreso) {

        List<Object> errores_validacion = new ArrayList<>();

        if (null == datosVendedor.getIdSistema()) {
            errores_validacion.add("No ha cargado ningún cliente");
        }

        if (" ".equals(tipoEgreso)) {
            errores_validacion.add("Debe seleccionar el tipo de egreso");
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        return true;
    }

    public boolean validacionesDetalleEgreso(JTable tablaEgresos, String tipoComprobante) {

        List<Object> errores_validacion = new ArrayList<>();

        if (tablaEgresos.getRowCount() == 0) {
            errores_validacion.add("No ha cargado ningún concepto de egreso");
        }

        for (int i = 0; i < tablaEgresos.getRowCount(); i++) {
            String descripcionProducto = tablaEgresos.getValueAt(i, 1).toString();

            if (descripcionProducto.length() > Constantes.LONGITUD_MAXIMA_DESCRIPCION_PRODUCTOS) {
                errores_validacion.add("El concepto de egreso supera los 255 caracteres!");
            }

            BigDecimal valorProducto = big.getMoneda(tablaEgresos.getValueAt(i, 3).toString());
            if (valorProducto.compareTo(BigDecimal.ZERO) <= 0) {
                errores_validacion.add("El costo del producto '" + descripcionProducto + "' debe ser mayor a " + simboloMoneda + "0");
            }

            int porcentajeIva = Integer.parseInt(tablaEgresos.getValueAt(i, 4).toString());
            if (!Constantes.TARIFAS_IVAS_PERMITIDOS.contains(porcentajeIva)) {
                errores_validacion.add("El IVA " + porcentajeIva + "% del concepto '" + descripcionProducto + "' no es válido. "
                        + "Los permitidos son: " + Constantes.TARIFAS_IVAS_PERMITIDOS.toString());
            }

            if (Constantes.esDocumentoSoporte(tipoComprobante)) {
                if (descripcionProducto.length() < Constantes.LONGITUD_MINIMA_DESCRIPCION_PRODUCTOS) {
                    errores_validacion.add("El concepto de egreso debe tener descripción más larga");
                }
            }
        }

        if (errores_validacion.size() > 0) {
            ControladorAlertas.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
