/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.FacturacionElectronica;

import Controlador.Alertas.ControladorAlertas;
import Utilidades.Constantes;
import clases.Instancias;
import Modelo.Terceros.ModeloContacto;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author sebastian.londono
 */
public class squemaFacturacionElectronica extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();

    private static final String ERRORDIAN = "ERRORDIAN";
    private static final String ERROR = "ERROR";

    public squemaFacturacionElectronica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaciones_facturacionElectronica(ModeloContacto datosCliente, String vendedor, Object[] datosValidacion, 
            boolean esNotaDebito, boolean esNotaCredito) {

        List<Object> errores_validacion = new ArrayList<>();

        try {
            Socket s = new Socket("www.google.com", 80);
            if (s.isConnected()) {
                System.out.println("Facturando electronicamente");
            }
        } catch (Exception e) {
            errores_validacion.add("No se puede facturar electrónicamente sin conexión a internet");
        }

        String identificadorCliente = Constantes.leerIdentificadorCliente();
        int numeroFacturasDisponibles = Integer.parseInt(instancias.getSqlPagos().obtenerNumeroConsecutivo(identificadorCliente)[0].toString());

        if (numeroFacturasDisponibles <= 0) {
            errores_validacion.add("No tiene movimientos electrónicas disponibles, comuniquiese con el proveedor");
        } else if (numeroFacturasDisponibles < 5) {
            alerts.alert("Quedan solo " + numeroFacturasDisponibles + " movimientos electrónicas.");
        } else {
            System.out.println("numero de movimientos: " + numeroFacturasDisponibles);
        }

        if (null == datosCliente.getId() || Constantes.CLIENTE_POR_DEFECTO.equals(datosCliente.getId())) {
            errores_validacion.add("Debe cargar un cliente para facturar electrónicamente");
        }

        if (datosCliente.getDepartamento() != null) {
            if ("".equals(datosCliente.getDepartamento())) {
                errores_validacion.add("El cliente debe tener un departamento");
            }
        } else {
            errores_validacion.add("El cliente debe tener un departamento");
        }

        if (datosCliente.getCiudad() != null) {
            if ("".equals(datosCliente.getCiudad())) {
                errores_validacion.add("El cliente debe tener una ciudad");
            }
        } else {
            errores_validacion.add("El cliente debe tener una ciudad");
        }

        if (datosCliente.getCodigoPostal() != null) {
            if ("".equals(datosCliente.getCodigoPostal())) {
                errores_validacion.add("El cliente debe tener codigo postal");
            }
        } else {
            errores_validacion.add("El cliente debe tener codigo postal");
        }

        if (datosCliente.getDireccion() != null) {
            if (datosCliente.getDireccion().equals("")) {
                errores_validacion.add("El cliente debe tener una dirección");
            }
        } else {
            errores_validacion.add("El cliente debe tener una dirección");
        }

        if (datosCliente.getEmail() != null) {
            if (datosCliente.getEmail().equals("")) {
                errores_validacion.add("El cliente debe tener un email");
            }
        } else {
            errores_validacion.add("El cliente debe tener un email");
        }

        if (null != datosCliente.getId() && datosCliente.getId().contains("-")) {
            if (null == datosCliente.getId().split("-")[1]) {
                errores_validacion.add("El cliente debe tener dígito de verificación");
            }
        } else {
            errores_validacion.add("El cliente debe tener dígito de verificación");
        }

        if (vendedor.equals("Seleccione un vendedor") || vendedor.equals("") || vendedor.equals(" ")) {
            errores_validacion.add("Debe seleccionar un vendedor");
        }

        if (esNotaDebito) {
            if (datosValidacion[0].equals("")) {
                errores_validacion.add("Debe cargar la factura relacionada");
            }

            if (datosValidacion[1].equals("")) {
                errores_validacion.add("Debe ingresar la observación de la nota debito");
            }

            if ((Boolean) datosValidacion[2] == true) {
                errores_validacion.add("No ha seleccionado ningún concepto");
            }

            if (instancias.getIdND() == null || instancias.getIdND().equals("")) {
                errores_validacion.add("El prefijo de la nota debito es obligatorio");
            }
        }

        if (esNotaCredito) {
            if ((Boolean) datosValidacion[0] == true) {
                errores_validacion.add("No ha seleccionado ningún concepto");
            }

            if (datosValidacion[1].equals("")) {
                errores_validacion.add("Debe ingresar la observación de la nota crédito");
            }

            if (instancias.getIdNC() == null || instancias.getIdNC().equals("")) {
                errores_validacion.add("El prefijo de la nota crédito es obligatorio");
            }
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
