/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.Facturacion;

import Controlador.Alertas.ControladorAlertas;
import Enums.TipoDocumento;
import Utilidades.Constantes;
import clases.Instancias;
import clases.big;
import Modelo.Terceros.ModeloContacto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author sebastian.londono
 */
public class squemaFacturacion extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();
    private String simboloMoneda = instancias.getSimbolo();

    public squemaFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaciones_facturacion(ModeloContacto datosCliente) {

        List<Object> errores_validacion = new ArrayList<>();
        if (null == datosCliente.getIdSistema()) {
            errores_validacion.add("No ha cargado ningún cliente");
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        return true;
    }

    private String obtenerValorTabla(JTable tablaProductos, String campoTabla, int posicionProducto, boolean esNotaCredito, boolean esNotaDebito) {
        switch (campoTabla) {
            case "ID_SISTEMA":
                if (esNotaCredito) {
                    return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_ID_SISTEMA_NOTA_CREDITO).toString();
                } else {
                    return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_ID_SISTEMA).toString();
                }
            case "DESCRIPCION_PRODUCTO":
                return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_DESCRIPCION_PRODUCTO).toString();
            case "UNIDAD_MEDIDA":
                if (esNotaCredito) {
                    return tablaProductos.getValueAt(posicionProducto, 21).toString();
                } else if (esNotaDebito) {
                    return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_UNIDAD_MEDIDA_NOTA_DEBITO).toString();
                } else {
                    return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_UNIDAD_MEDIDA).toString();
                }
            case "PORCENTAJE_IVA":
                if (esNotaCredito) {
                    return tablaProductos.getValueAt(posicionProducto, 6).toString();
                } else {
                    return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_PORCENTAJE_IVA).toString();
                }
            case "PORCENTAJE_IMPOCONSUMO":
                if (esNotaCredito) {
                    return tablaProductos.getValueAt(posicionProducto, 8).toString();
                } else {
                    return tablaProductos.getValueAt(posicionProducto, Constantes.COLUMNA_PORCENTAJE_IMPOCONSUMO).toString();
                }
            default:
                return "";
        }
    }

    public boolean validaciones_detalle_facturacion(JTable tablaProductos, String tipoComprobante, String tipoProceso) {

        List<Object> errores_validacion = new ArrayList<>();
        List<Object> alertas_validacion = new ArrayList<>();
        boolean esNotaCredito = tipoProceso.equals(TipoDocumento.NOTA_CREDITO.getValor());
        boolean esNotaDebito = tipoProceso.equals(TipoDocumento.NOTA_DEBITO.getValor());

        if (tablaProductos.getRowCount() == 0 && !tipoProceso.equals(TipoDocumento.NOTA_CREDITO.getValor())) {
            errores_validacion.add("No ha cargado ningún producto");
        }

        for (int i = 0; i < tablaProductos.getRowCount(); i++) {
            String descripcionProducto = obtenerValorTabla(tablaProductos, "DESCRIPCION_PRODUCTO", i, esNotaCredito, esNotaDebito);
            String unidadMedida = obtenerValorTabla(tablaProductos, "UNIDAD_MEDIDA", i, esNotaCredito, esNotaDebito);

            if (descripcionProducto.length() > Constantes.LONGITUD_MAXIMA_DESCRIPCION_PRODUCTOS) {
                errores_validacion.add("El producto '" + descripcionProducto + "' supera los 255 caracteres!");
            }

            BigDecimal valorProducto = big.getMoneda(tablaProductos.getValueAt(i, Constantes.COLUMNA_VALOR_PRODUCTO).toString());
            if (valorProducto.compareTo(BigDecimal.ZERO) <= 0) {
                errores_validacion.add("El valor unitario del producto '" + descripcionProducto + "' debe ser mayor a " + simboloMoneda + "0");
            }

            if (Constantes.esFacturacionElectronica(tipoComprobante)
                    && (tipoProceso.equals(TipoDocumento.FACTURACION.getValor())
                    || tipoProceso.equals(TipoDocumento.NOTA_DEBITO.getValor())
                    || tipoProceso.equals(TipoDocumento.NOTA_CREDITO.getValor()))) {
                if (descripcionProducto.length() < Constantes.LONGITUD_MINIMA_DESCRIPCION_PRODUCTOS) {
                    errores_validacion.add("El producto '" + descripcionProducto + "' debe tener descripción más larga");
                }

                if ("".equals(unidadMedida)) {
                    errores_validacion.add("El producto '" + descripcionProducto + "' debe tener unidad de medida");
                }

                String codigoUnidadMedida = instancias.getSql().getDatosMedidas(unidadMedida);
                if (null == codigoUnidadMedida) {
                    errores_validacion.add("El producto '" + descripcionProducto + "' debe tener unidad de medida válida");
                }

                int porcentajeIva = Integer.parseInt(obtenerValorTabla(tablaProductos, "PORCENTAJE_IVA", i, esNotaCredito, esNotaDebito));
                int porcentajeImpoconsumo = Integer.parseInt(obtenerValorTabla(tablaProductos, "PORCENTAJE_IMPOCONSUMO", i, esNotaCredito, esNotaDebito));

                if (!Constantes.TARIFAS_IVAS_PERMITIDOS.contains(porcentajeIva)) {
                    errores_validacion.add("El IVA " + porcentajeIva + "% del producto '" + descripcionProducto + "' no es válido. "
                            + "Los permitidos son: " + Constantes.TARIFAS_IVAS_PERMITIDOS.toString());
                }

                if (!Constantes.TARIFAS_IMPOCONSUMO_PERMITIDOS.contains(porcentajeImpoconsumo)) {
                    errores_validacion.add("El IMPOCONSUMO " + porcentajeImpoconsumo + "% del producto '" + descripcionProducto + "' "
                            + "no es válido. Los permitidos son: " + Constantes.TARIFAS_IMPOCONSUMO_PERMITIDOS.toString());
                }
            }

            String idSistema = obtenerValorTabla(tablaProductos, "ID_SISTEMA", i, esNotaCredito, esNotaDebito);
            String costoProducto = instancias.getSql().obtenerUltimoCostoProducto(idSistema);
            if (valorProducto.compareTo(big.getBigDecimal(costoProducto)) < 0) {
                alertas_validacion.add("El producto '" + descripcionProducto + "' se esta facturando por debajo del costo");
            }
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        if (alertas_validacion.size() > 0) {
            boolean respuesta = alerts.alertaGrandeListado("Se presentaron las siguientes alertas...", alertas_validacion, true);
            if (!respuesta) {
                return false;
            }
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
