/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.Configuraciones;

import Controlador.Alertas.ControladorAlertas;
import Utilidades.Constantes;
import clases.Instancias;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author sebastian.londono
 */
public class squemaResoluciones extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    private Instancias instancias;

    public squemaResoluciones() {
        initComponents();

        instancias = Instancias.getInstancias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionesResoluciones(JTable tablaResoluciones) {

        List<Object> errores_validacion = new ArrayList<>();

        for (int i = 0; i < tablaResoluciones.getRowCount(); i++) {
            String descripcionComprobante = tablaResoluciones.getValueAt(i, 1).toString();
            String tipoComprobante = tablaResoluciones.getValueAt(i, 2).toString();
            String disenho = tablaResoluciones.getValueAt(i, 3).toString();
            String numeroResolucion = tablaResoluciones.getValueAt(i, 4).toString();
            String prefijo = tablaResoluciones.getValueAt(i, 5).toString();
            String fechaInicio = tablaResoluciones.getValueAt(i, 6).toString();
            String fechaFinal = tablaResoluciones.getValueAt(i, 7).toString();
            String numeracionDel = tablaResoluciones.getValueAt(i, 8).toString();
            String numeracionHasta = tablaResoluciones.getValueAt(i, 9).toString();

            if (descripcionComprobante.equals("")) {
                errores_validacion.add("Debe ingresar la descripción del comprobante en la fila #" + (i + 1));
            }

            if (tipoComprobante.equals("")) {
                errores_validacion.add("Debe seleccionar un tipo de comprobante en la fila #" + (i + 1));
            }

            if (disenho.equals("") && tipoComprobante.equals(Constantes.FACTURACION_ELECTRONICA)) {
                errores_validacion.add("Debe ingresar el número del diseño en la fila #" + (i + 1));
            }

            if (numeroResolucion.equals("")) {
                errores_validacion.add("Debe ingresar el número de resolución en la fila #" + (i + 1));
            }

            if (prefijo.equals("") && instancias.getRegimen().equals("") && !esCompraVentaNormal(tipoComprobante)) {
                errores_validacion.add("Debe ingresar el prefijo de resolución en la fila #" + (i + 1));
            }

            if (fechaInicio.equals("")) {
                errores_validacion.add("Debe seleccionar la fecha de inicio de la resolución en la fila #" + (i + 1));
            }

            if (fechaFinal.equals("")) {
                errores_validacion.add("Debe seleccionar la fecha de finalización de la resolución en la fila #" + (i + 1));
            }

            if (numeracionDel.equals("")) {
                errores_validacion.add("Debe ingresar el inicio de la numeración del comprobante en la fila #" + (i + 1));
            } else {
                try {
                    Integer.parseInt(numeracionDel);
                } catch (Exception e) {
                    errores_validacion.add("Debe ingresar un número en el inicio de la numeración del comprobante en la fila #" + (i + 1));
                }
            }

            if (numeracionHasta.equals("")) {
                errores_validacion.add("Debe ingresar el final de la numeración del comprobante en la fila #" + (i + 1));
            } else {
                try {
                    Integer.parseInt(numeracionHasta);
                } catch (Exception e) {
                    errores_validacion.add("Debe ingresar un número en el final de la numeración del comprobante en la fila #" + (i + 1));
                }
            }
        }

        if (errores_validacion.size() > 0) {
            ControladorAlertas.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        return true;
    }

    private boolean esCompraVentaNormal(String tipoResolucion) {
        return tipoResolucion.equals("Factura Normal") || tipoResolucion.equals("Compra Normal");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
