/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.Compras;

import Controlador.Alertas.ControladorAlertas;
import Enums.TipoDocumento;
import Utilidades.Constantes;
import clases.Instancias;
import clases.big;
import Modelo.Terceros.ModeloContacto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author sebastian.londono
 */
public class squemaCompras extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();
    private String simboloMoneda = instancias.getSimbolo();

    public squemaCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionesCompra(ModeloContacto datosVendedor, String tipoProceso, String numeroFactura, String tipoIngreso, String diasPlazo) {

        List<Object> errores_validacion = new ArrayList<>();
        List<Object> alertas_validacion = new ArrayList<>();

        if (null == datosVendedor.getIdSistema()) {
            errores_validacion.add("No ha cargado ningún proveedor");
        }

        if (tipoProceso.equals(TipoDocumento.COMPRA.getValor())) {
            if (numeroFactura.equals("") && !tipoIngreso.equals("OTRO INGRESO")) {
                errores_validacion.add("Debe ingresar el número de la factura");
            }

            Boolean existeFactura = instancias.getSql().existeFacturaCompra(datosVendedor.getIdSistema(), numeroFactura);
            if (existeFactura) {
                alertas_validacion.add("El número de factura para este vendedor ya existe");
            }

            if (diasPlazo.equals("") || diasPlazo.equals("0")) {
                alertas_validacion.add("No ha ingresado los días de plazo");
            }
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        if (alertas_validacion.size() > 0) {
            boolean respuesta = alerts.alertaGrandeListado("Se presentaron las siguientes alertas...", alertas_validacion, true);
            if (!respuesta) {
                return false;
            }
        }

        return true;
    }

    public boolean validacionesDetalleCompra(JTable tablaProductos, String tipoComprobante, String tipoProceso) {

        List<Object> errores_validacion = new ArrayList<>();

        if (tablaProductos.getRowCount() == 0) {
            errores_validacion.add("No ha cargado ningún producto");
        }

        for (int i = 0; i < tablaProductos.getRowCount(); i++) {
            String descripcionProducto = tablaProductos.getValueAt(i, 1).toString();
            String unidadMedida = tablaProductos.getValueAt(i, 10).toString();

            if (descripcionProducto.length() > Constantes.LONGITUD_MAXIMA_DESCRIPCION_PRODUCTOS) {
                errores_validacion.add("El producto '" + descripcionProducto + "' supera los 255 caracteres!");
            }

            BigDecimal valorProducto = big.getMoneda(tablaProductos.getValueAt(i, 2).toString());
            if (valorProducto.compareTo(BigDecimal.ZERO) <= 0) {
                errores_validacion.add("El costo del producto '" + descripcionProducto + "' debe ser mayor a " + simboloMoneda + "0");
            }

            if (Constantes.esDocumentoSoporte(tipoComprobante) && tipoProceso.equals(TipoDocumento.COMPRA.getValor())) {

                if (descripcionProducto.length() < Constantes.LONGITUD_MINIMA_DESCRIPCION_PRODUCTOS) {
                    errores_validacion.add("El producto '" + descripcionProducto + "' debe tener descripción más larga");
                }

                if ("".equals(unidadMedida)) {
                    errores_validacion.add("El producto '" + descripcionProducto + "' debe tener unidad de medida");
                }

                String codigoUnidadMedida = instancias.getSql().getDatosMedidas(unidadMedida);
                if (null == codigoUnidadMedida) {
                    errores_validacion.add("El producto '" + descripcionProducto + "' debe tener unidad de medida válida");
                }

                int porcentajeIva = Integer.parseInt(tablaProductos.getValueAt(i, 7).toString());
                int porcentajeImpoconsumo = Integer.parseInt(tablaProductos.getValueAt(i, 8).toString());

                if (!Constantes.TARIFAS_IVAS_PERMITIDOS.contains(porcentajeIva)) {
                    errores_validacion.add("El IVA " + porcentajeIva + "% del producto '" + descripcionProducto + "' no es válido. "
                            + "Los permitidos son: " + Constantes.TARIFAS_IVAS_PERMITIDOS.toString());
                }

                if (!Constantes.TARIFAS_IMPOCONSUMO_PERMITIDOS.contains(porcentajeImpoconsumo)) {
                    errores_validacion.add("El IMPOCONSUMO " + porcentajeImpoconsumo + "% del producto '" + descripcionProducto + "' "
                            + "no es válido. Los permitidos son: " + Constantes.TARIFAS_IMPOCONSUMO_PERMITIDOS.toString());
                }
            }
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
