package Vista.Restaurante;

import Controlador.Alertas.ControladorAlertas;
import Modelo.Ventas.ModeloMesa;
import Utilidades.DatosMaestra;
import clases.Instancias;
import clases.big;
import clases.metodosGenerales;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class VistaCambiarMesa extends javax.swing.JDialog {

    metodosGenerales metodos = new metodosGenerales();
    private final Instancias instancias;
    private final PanelMesas panelMesas;
    private final String facturaGeneral;
    private List<ModeloMesa> listaMesas = new ArrayList<>();

    public VistaCambiarMesa(java.awt.Frame parent, boolean modal, String factura) {
        super(parent, modal);
        initComponents();
        this.setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width, java.awt.Toolkit.getDefaultToolkit().getScreenSize().height);

        instancias = Instancias.getInstancias();

        facturaGeneral = factura;

        this.setLocationRelativeTo(null);

        panelMesas = new PanelMesas();
        panelMesas.setListener(new PanelMesas.ListenerMesa() {
            @Override
            public void mesaSeleccionada(ModeloMesa mesa) {
                manejarClickMesa(mesa);
            }
        });
        jScrollPane11.setViewportView(panelMesas);

        cargarDimensiones();
        cargarRegistrosMesas();
        cargarRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMesa = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambiar mesa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblMesa.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesa.setText("ESCOJA LA NUEVA MESA");

        tblMesas.setBackground(new java.awt.Color(255, 0, 0));
        tblMesas.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMesas.setRowHeight(100);
        tblMesas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblMesas.setSelectionForeground(new java.awt.Color(204, 204, 204));
        tblMesas.getTableHeader().setResizingAllowed(false);
        tblMesas.getTableHeader().setReorderingAllowed(false);
        tblMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesasMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblMesas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblMesa)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesasMouseClicked
        // delegado a PanelMesas.ListenerMesa → manejarClickMesa()
    }//GEN-LAST:event_tblMesasMouseClicked

    private void cargarDimensiones() {
        int filas = Integer.parseInt(DatosMaestra.getFilas());
        int columnas = Integer.parseInt(DatosMaestra.getColumnas());
        panelMesas.setDimensiones(filas, columnas);
    }

    private void cargarRegistrosMesas() {
        listaMesas = new ArrayList<>();
        Object[][] mesas = instancias.getSql().getPosicionesMesas();

        for (Object[] mesa : mesas) {
            String[] coords = mesa[0].toString().split(",");
            int rawFila = Integer.parseInt(coords[0]);
            int columna = Integer.parseInt(coords[1]);
            int fila = (rawFila - 1) / 2;
            String nombre = mesa[1].toString();
            listaMesas.add(new ModeloMesa(fila, columna, nombre));
        }
        panelMesas.setMesas(listaMesas);
    }

    private void cargarRegistros() {
        Object[][] congeladas = instancias.getSql().getDatosCongelada1();

        if (congeladas.length > 0) {
            for (Object[] congelada : congeladas) {
                if (congelada[0] == null) {
                    continue;
                }
                String lugar = congelada[2].toString();
                BigDecimal total = big.getBigDecimal(congelada[1]);
                String turno = "";
                if (congelada[3] != null && !congelada[3].toString().isEmpty()) {
                    turno = congelada[3].toString();
                }
                for (ModeloMesa mesa : listaMesas) {
                    if (mesa.getNombre().equals(lugar)) {
                        mesa.setOcupada(true);
                        mesa.setTotal(total);
                        mesa.setTurno(turno);
                        break;
                    }
                }
            }
        }
        panelMesas.setMesas(listaMesas);
    }

    private void manejarClickMesa(ModeloMesa mesa) {
        if (mesa.isOcupada()) {
            ControladorAlertas.alert("¡Mesa ocupada!");
            return;
        }

        instancias.getSql().cambiarMesa(facturaGeneral, mesa.getNombre());
        instancias.getMesa1().setCambioMesa(true);
        ControladorAlertas.alertSuccess("Mesa cambiada correctamente!");
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JTable tblMesas;
    // End of variables declaration//GEN-END:variables
}
