/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador.Alertas;

import Vistas.Alertas.AlertList;
import Vistas.Alertas.BigAlert;
import Vistas.Alertas.Fail;
import Vistas.Alertas.Option;
import Vistas.Alertas.Success;
import Vistas.Alertas.alert;
import java.util.List;

/**
 *
 * @author sebastian.londono
 */
public class controladorAlertas extends javax.swing.JPanel {

    /**
     * Creates new form showAlerts
     */
    public controladorAlertas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void alertFail(String message) {
        Fail messageError = new Fail(null, true, message);
        messageError.setVisible(true);
    }

    public static void alertSuccess(String message) {
        Success messageSuccess = new Success(null, true, message);
        messageSuccess.setVisible(true);
    }

    public static void alert(String message) {
        alert messageAlert = new alert(null, true, message);
        messageAlert.setVisible(true);
    }

    public static void bigAlert(String message) {
        BigAlert messageBigAlert = new BigAlert(null, true, message);
        messageBigAlert.setVisible(true);
    }

    public static Boolean option(String ask) {
        Option messageOption = new Option(null, true, ask);
        messageOption.setVisible(true);
        return messageOption.answer;
    }

    public static void alertaGrandeListado(String message, List<Object> listadoDetalles) {
        AlertList mensajeAlertaListado = new AlertList(null, true, message, listadoDetalles);
        mensajeAlertaListado.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
