/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.DocumentosElectronicos;

import Controlador.Alertas.ControladorAlertas;
import clases.Instancias;
import java.util.ArrayList;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author sebastian.londono
 */
public class squemaDocumentosElectronicos extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();

    private static final String ERRORDIAN = "ERRORDIAN";
    private static final String ERROR = "ERROR";

    public squemaDocumentosElectronicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validaciones_respuesta(String respuesta) throws JSONException {
        System.out.println("Respuesta servicio: " + respuesta);
        List<Object> listadoDetalles = new ArrayList<>();
        if (respuesta.startsWith("{")) {
            JSONObject respuestaJSON = new JSONObject(respuesta);
            String estadoTransaccion = respuestaJSON.getJSONObject("estado").getString("codigo");
            if (estadoTransaccion.equals(ERROR) || estadoTransaccion.equals(ERRORDIAN)) {
                JSONArray listadoErrores = respuestaJSON.getJSONObject("estado").getJSONArray("errores");

                if (listadoErrores.length() > 0) {
                    for (int i = 0; i < listadoErrores.length(); i++) {
                        listadoDetalles.add(listadoErrores.get(i));
                    }
                } else {
                    String descripcionError = respuestaJSON.getJSONObject("estado").getString("descripcion");
                    listadoDetalles.add(descripcionError);
                }
                
                alerts.alertaGrandeListado("Se presentaron los siguientes errores...", listadoDetalles, false);
                return false;
            } else {
                return true;
            }
        } else {
            System.out.println("Respuesta diferente a JSON: " + respuesta);
            alerts.alertFail("Error al generar factura electrónica");
            return false;
        }
    }

    public boolean validaciones_respuesta_token(String respuesta) throws JSONException {
        System.out.println("Respuesta: " + respuesta);
        JSONObject respuestaAJSON = new JSONObject(respuesta);
        String estadoTransaccion = respuestaAJSON.getString("codigo");

        if (estadoTransaccion.equals("ERROR")) {
            alerts.alert("Hubo un error al generar el token");
            return false;
        } else {
            String tokenGenerado = respuestaAJSON.getString("token");
            System.out.println("Token: " + tokenGenerado);
            instancias.setTokenEmisor(tokenGenerado);
            return true;
        }
    }

    public boolean validaciones_respuesta_resoluciones(String respuesta) throws JSONException {
        List<Object> listadoDetalles = new ArrayList<>();
        if (respuesta.startsWith("{")) {

            JSONObject respuestaJSON = new JSONObject(respuesta);

            if (respuesta.contains("resultado")) {
                String resultado = respuestaJSON.get("resultado").toString();
                String estadoTransaccion = respuestaJSON.getJSONArray("resoluciones").toString();
                listadoDetalles.add(estadoTransaccion);
                alerts.alertaGrandeListado(resultado, listadoDetalles, false);
            } else {
                String estadoTransaccion = respuestaJSON.getJSONObject("estado").getString("codigo");
                if (estadoTransaccion.equals(ERROR) || estadoTransaccion.equals(ERRORDIAN)) {
                    listadoDetalles.add(respuestaJSON.getJSONObject("estado").getString("descripcion"));
                    alerts.alertaGrandeListado("Se presentaron los siguientes errores...", listadoDetalles, false);
                    return false;
                }
            }
        } else {
            alerts.alertFail("Error al generar factura electrónica");
            return false;
        }

        //espuesta: {"estado":{"codigo":"ERROR","descripcion":"No registra prefijos asociados al c\u00f3digo de software: 1a197f09-5b34-4985-8ab6-3d87c0a58af6."}}
        return true;
    }

    public boolean validaciones_respuesta_consulta_factura_electronica(String respuesta) throws JSONException {
        List<Object> listadoDetalles = new ArrayList<>();
        if (respuesta.startsWith("[")) {
            JSONObject datos = new JSONArray(respuesta).getJSONObject(0);
            String estadoTransaccion = datos.getJSONObject("estado").getString("codigoestado");
            if (estadoTransaccion.equals(ERROR) || estadoTransaccion.equals(ERRORDIAN)) {
                JSONArray listadoErrores = datos.getJSONObject("estado").getJSONArray("errores");
                for (int i = 0; i < listadoErrores.length(); i++) {
                    listadoDetalles.add(listadoErrores.get(i));
                }
                alerts.alertaGrandeListado("Se presentaron los siguientes errores...", listadoDetalles, false);
                return false;
            } else {
                return true;
            }
        } else {
            System.out.println("Respuesta diferente a JSON: " + respuesta);
            alerts.alertFail("Error al generar factura electrónica");
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
