/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.Terceros;

import Controlador.Alertas.ControladorAlertas;
import Modelo.Terceros.ModeloDatosVehiculo;
import Utilidades.Constantes;
import clases.Instancias;
import Modelo.Terceros.ModeloContacto;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author sebastian.londono
 */
public class squemaDatosVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();

    public squemaDatosVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionesDatosVehiculo(ModeloDatosVehiculo datosVehiculo, JTable vehiculosCargados) {

        List<Object> errores_validacion = new ArrayList<>();

        if (datosVehiculo.getPlaca() != null) {
            if ("".equals(datosVehiculo.getPlaca())) {
                errores_validacion.add("Debe ingresar la placa del vehículo");
            } else {
                String placa = datosVehiculo.getPlaca();
                Object[][] placas = instancias.getSql().getPlacas();
                for (int i = 0; i < placas.length; i++) {
                    if (placa.equals(placas[i][1])) {
                        errores_validacion.add("La placa ya existe en la base de datos");
                        break;
                    }
                }

                for (int i = 0; i < vehiculosCargados.getRowCount(); i++) {
                    if (placa.equals(vehiculosCargados.getValueAt(i, 0))) {
                        errores_validacion.add("La placa ya se encuentra registrada");
                        break;
                    }
                }
            }
        } else {
            errores_validacion.add("Debe ingresar la placa del vehículo");
        }

        if (datosVehiculo.getTipoVehiculo() != null) {
            if ("".equals(datosVehiculo.getPlaca())) {
                errores_validacion.add("Debe ingresar el tipo del vehículo");
            }
        } else {
            errores_validacion.add("Debe ingresar el tipo del vehículo");
        }

        if (datosVehiculo.getMarca() != null) {
            if ("".equals(datosVehiculo.getMarca())) {
                errores_validacion.add("Debe ingresar la marca del vehículo");
            }
        } else {
            errores_validacion.add("Debe ingresar la marca del vehículo");
        }

        if (datosVehiculo.getModelo() != null) {
            if ("".equals(datosVehiculo.getModelo())) {
                errores_validacion.add("Debe ingresar el modelo del vehículo");
            }
        } else {
            errores_validacion.add("Debe ingresar el modelo del vehículo");
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
