/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validaciones.Terceros;

import Controlador.Alertas.ControladorAlertas;
import Modelo.Terceros.ModeloContacto;
import Modelo.Terceros.ModeloDatosVehiculo;
import clases.Instancias;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author sebastian.londono
 */
public class squemaDatosContacto extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    Instancias instancias = Instancias.getInstancias();
    ControladorAlertas alerts = new ControladorAlertas();

    public squemaDatosContacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validacionesDatosContacto(ModeloContacto datosContacto, boolean esTipoPaciente, boolean esFacturacionElectronica,
            String digitoVerificacion, ModeloContacto consultaDatosContacto) {

        List<Object> errores_validacion = new ArrayList<>();

        if (datosContacto.getTipo() != null) {
            if ("".equals(datosContacto.getTipo())) {
                errores_validacion.add("Debe ingresar el tipo de identificación");
            }
        } else {
            errores_validacion.add("Debe ingresar el tipo de identificación");
        }

        if (datosContacto.getId() != null) {
            if ("".equals(datosContacto.getId())) {
                errores_validacion.add("Debe ingresar la identificación");
            } else {
                if (consultaDatosContacto.getId() != null) {
                    errores_validacion.add(esTipoPaciente ? "El paciente ya existe" : "El cliente ya existe");
                }
            }
        } else {
            errores_validacion.add("Debe ingresar la identificación");
        }

        if (datosContacto.getNombre() != null) {
            if ("".equals(datosContacto.getNombre())) {
                errores_validacion.add("Debe ingresar el nombre");
            }
        } else {
            errores_validacion.add("Debe ingresar el nombre");
        }

        if (datosContacto.getTelefono() != null) {
            if ("".equals(datosContacto.getTelefono())) {
                errores_validacion.add("Debe ingresar el teléfono");
            }
        } else {
            errores_validacion.add("Debe ingresar el teléfono");
        }

        if (esTipoPaciente || esFacturacionElectronica) {
            if (datosContacto.getDepartamento() != null) {
                if (" ".equals(datosContacto.getDepartamento())) {
                    errores_validacion.add("Debe seleccionar el departamento");
                }
            } else {
                errores_validacion.add("Debe seleccionar el departamento");
            }

            if (datosContacto.getCiudad() != null) {
                if (" ".equals(datosContacto.getCiudad())) {
                    errores_validacion.add("Debe seleccionar la ciudad");
                }
            } else {
                errores_validacion.add("Debe seleccionar la ciudad");
            }
        }

        if (esFacturacionElectronica) {
            if (datosContacto.getEmail() != null) {
                if ("".equals(datosContacto.getEmail())) {
                    errores_validacion.add("Debe ingresar el correo electrónico");
                }
            } else {
                errores_validacion.add("Debe ingresar el correo electrónico");
            }

            if (datosContacto.getCodigoPostal() != null) {
                if (" ".equals(datosContacto.getCodigoPostal())) {
                    errores_validacion.add("Debe seleccionar el código postal");
                }
            } else {
                errores_validacion.add("Debe seleccionar el código postal");
            }
        }

        if (esTipoPaciente) {
            if (datosContacto.getEps() != null) {
                if ("".equals(datosContacto.getEps())) {
                    errores_validacion.add("Debe cargar una EPS");
                }
            } else {
                errores_validacion.add("Debe cargar una EPS");
            }

            if (datosContacto.getRegimen() != null) {
                if (" ".equals(datosContacto.getRegimen())) {
                    errores_validacion.add("Debe seleccionar un régimen");
                }
            } else {
                errores_validacion.add("Debe seleccionar un régimen");
            }

            if (datosContacto.getAfiliado() != null) {
                if (" ".equals(datosContacto.getAfiliado())) {
                    errores_validacion.add("Debe seleccionar el tipo de afiliado");
                }
            } else {
                errores_validacion.add("Debe seleccionar el tipo de afiliado");
            }

            if (datosContacto.getTipoTrabajador() != null) {
                if (" ".equals(datosContacto.getTipoTrabajador())) {
                    errores_validacion.add("Debe seleccionar el tipo de trabajador");
                }
            } else {
                errores_validacion.add("Debe seleccionar el tipo de trabajador");
            }
        }

        if (errores_validacion.size() > 0) {
            alerts.alertaGrandeListado("Se presentaron los siguientes errores...", errores_validacion, false);
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
